### ISSUE TITLE
Auto Layout support

### ISSUE THREAD

**Issue by Macjon** [Dromaguirre/Popsicle#9]
I've seen that the slideshow doesn't support auto layout. Is it a lot of work to add auto layout support?

**Comment by Dromaguirre** [comment]
Hi there.

First of all, I apologize for being absent for so long. I'm in my last year of high school and I have to study like crazy.

After thinking about this (and other reported issues and feature requests) for a while, I've come to a decision: decoupling the keyframing/interpolation logic from the view logic into two different projects.

For the last few months, I've been working on a value interpolation framework called Lollipop, highly inspired by both (https://github.com/facebook/pop)[__Facebook's pop__] and (https://github.com/IFTTT/JazzHands)[__IFTTT's JazzHands__], providing and improving the best of both frameworks, such as custom value interpolation and UIKit agnosticism.

In addition to that, I currently have another project called (https://github.com/Dromaguirre/DRPaginatedScrollView)[DRPaginatedScrollView], which I'm planning to improve in order to provide full auto layout support and some other nice features. That way, you can use it as a simple, easy-to-use paginated scroll view, or combine it with Lollipop in order to get some fancy transitions.

Although Lollipop is almost ready to ship, the new DRPaginatedScrollView still needs some work.

My idea is to replace DRDynamicSlideShow with Lollipop and update DRPaginatedScrollView to 2.0. What's your opinion on this? Also, should I release Lollipop as soon as it's ready, or release both Lollipop and DRPaginatedScrollView 2.0 at the same time?

**Comment by Dromaguirre** [comment]
Hi there, @Macjon.

I just released Popsicle, the evolution of DRDynamicSlideShow. Just so you know, you can now animate Auto Layout constraints constants through `PSFloatInterpolation`, although there isn't (still) a way of interpolating `NSLayoutConstraints` directly. Give me some time.
